### ISSUE TITLE
Improve services URL handling

### ISSUE THREAD

**Issue by g-nogueira** [g-nogueira/streamdeck-creator-fe#6]
Currently, the service URL is hardcoded on the code. We should use at least env variables. For example:

```yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"

    environment:
      - SERVICE_URL=<url>
```
